name: Build examples for esp32arduino @ 3.4.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build on PlatformIO
      run: bash ci/build-platformio.sh esp32arduinoV340

